version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
      android-gradle:
        patterns:
          - "com.android.tools.build*"
      androidx:
        patterns:
          - "androidx*"
      google:
        patterns:
          - "com.google.*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
